### ISSUE TITLE
hyperkube source?

### ISSUE THREAD

**Issue by cdrage** [cloudgear-net/demo-kubernetes#1]
are you able to upload the hyperkube source to github?

**Comment by geku** [comment]
The source for the hyperkube image can be found in the Kubernetes repository:
https://github.com/GoogleCloudPlatform/kubernetes/tree/master/cluster/images/hyperkube

I need to check again if Google provides up to date images, at the time of writing this was not the case and therefore I had to build the images myself.

To build the image yourself you can basically run `make` but you need to change the `Makefile`: the image tag needs to be changed and no push should be executed.

**Comment by cdrage** [comment]
Ahhh thank you :) closin'

p.s. sorry for the delay
